{% set name = "visidata" %}
{% set version = "2.3" %}
{% set sha256 = "408cfbe0250aeb4c58b7e80719de0242fd34754c3a9c228c0ae6eccb5ba01231" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - python-dateutil
    - requests
    - lxml
    - openpyxl
    - xlrd

test:
  commands:
    - pip3 install setuptools
    - vd --version

about:
  home: https://github.com/saulpw/visidata
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A terminal interface for exploring and arranging tabular data.'

  description: |
    VisiData is a multipurpose terminal utility for exploring, cleaning,
    restructuring and analysing tabular data. Current supported sources are
    TSV, CSV, fixed-width text, JSON, SQLite, HTTP, HTML, .xls, and .xlsx
    (Microsoft Excel).
  doc_url: https://visidata.org/docs
  dev_url: https://github.com/saulpw/visidata

extra:
  recipe-maintainers:
    - anjakefala
