travis:
  secure:
    BINSTAR_TOKEN: tZaRCMNVtNUj1XIkXOQUWoNMmRlZznMYAVuFeerdcgv+djJvgSldr5cBqUMS3WkY8DxjFnFDFt2h9cJdZaC0O25Zaxhr23KjjNLs8IeDDNfydVAPLyD8Z+5qeQc1PFDq6PgK3VikqFvHlpqs8Mk+Ge2hJJXXfxyzJr/rT+wkNXpPIREYziUaY2lqa/z8pGaRN51zavx94BRvjBsN96OdJb9WoqmOuecrhCpOvAKRdumiBUUlZoh50HysfkYzzHftzTy8pcspmSF+lIU0kLf/uGMfZN/ciNLwameMAcXxaE3EM3mEzYEkk7U+g6JuDAYMR8Cb8uL8Rlt61+fOLq2hPg5RWnrk2fFZawc370I8Y2hvgeqSM/MLWBQwx/62gsCwr17ysUWdNZNxkwmd5yh4TgPOE2/il5tHBI6f1kqnR31D3PaxhD4hfWmO1ANqnB7GwZdJq8vkUgbIsIrJyyEZB30Im/XAxdJbPIVU+E7YzTLmsmIFSrzYQ2bLanQSBv1kVVBdlBi4w+9mLyYEpEOVLHTnMv2zksgdQy4O+CPbGq0O9bCxKNOb1Fq/B/8D1ZvN87AslgKzM/HcyC7YjzKW9w3m/ck03RYAeK6msVt+0nKbFznrsu+uPeCnDHOZPvGF5/MGuCzlqeOZjSKLIwBtTX8DriaNx4Jqr3Wm/EAx4ts=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
